x-shared_environment: &shared_environment
  DATABASE_URL: postgresql+psycopg2://postgres:postgres@life-manager-db:5432/lifemanager
  REDIS_URL: redis://redis:6379/0
  # Enable debug mode in development
  DEBUG: "True"
  ENVIRONMENT: development
  # Disable email sending by default in development
  EMAILS_ENABLED: "False"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: life-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifemanager
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-lifemanager}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: life-manager-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API Service
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: life-manager-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      <<: *shared_environment
      # Override host for database and redis
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@life-manager-db:5432/lifemanager
      REDIS_URL: redis://redis:6379/0
      # First superuser credentials (only used on first run)
      FIRST_SUPERUSER_EMAIL: ${FIRST_SUPERUSER_EMAIL:-admin@example.com}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD:-ChangeMe123!}
      FIRST_SUPERUSER_FULL_NAME: "${FIRST_SUPERUSER_FULL_NAME:-Admin User}"
      # gRPC settings
      GRPC_PORT: 50051
    ports:
      - "${API_PORT:-8000}:8000"
      - "50051:50051"  # gRPC port
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect((\"localhost\", 8000))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # App Service
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: life-manager-app
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped

  # PGAdmin (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: life-manager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  # Redis Commander (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: life-manager-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    depends_on:
      - redis
    restart: unless-stopped

  # MailHog for email testing (optional)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: life-manager-mailhog
    ports:
      - "${MAILHOG_HTTP_PORT:-8026}:8025"  # Web UI (changed to 8026 to avoid conflicts)
      - "${MAILHOG_SMTP_PORT:-1026}:1025"  # SMTP server (changed to 1026 to avoid conflicts)
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

# Networks
networks:
  default:
    name: life-manager-network
    driver: bridge
