version: '3.8'

services:
  # Override app service for development
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: life-manager-app-dev
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped
