version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
      args:
        - POETRY_VERSION=1.4.2
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
      - PYTHONFAULTHANDLER=1
      - PYTHONHASHSEED=random
      - PIP_NO_CACHE_DIR=off
      - PIP_DISABLE_PIP_VERSION_CHECK=on
      - PIP_DEFAULT_TIMEOUT=100
      - POETRY_NO_INTERACTION=1
      - POETRY_VIRTUALENVS_CREATE=false
    ports:
      - "8000:8000"
      - "50051:50051"  # gRPC port
    command: >
      sh -c "alembic upgrade head &&
             python -m api"

  # Uncomment and customize if you have a frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=http://localhost:8000/api/v1
  #   command: npm start

  # Enable additional development tools
  pgadmin:
    ports:
      - "5050:80"

  redis-commander:
    ports:
      - "8081:8081"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: life-manager-mailhog
    ports:
      - "${MAILHOG_HTTP_PORT:-8026}:8025"  # Web UI
      - "${MAILHOG_SMTP_PORT:-1026}:1025"  # SMTP server
    restart: unless-stopped
