name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: lifemanager
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lifemanager
  PYTHONPATH: ${{ github.workspace }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: "1.7.0"
    
    - name: Install Python dependencies
      run: |
        make install
    
    - name: Test Docker commands
      run: |
        # Test basic Docker commands
        echo "Testing Docker installation..."
        docker --version
        
        # Test Make docker commands
        echo "\nTesting Make docker commands..."
        cp .env.example .env
        make docker-up
        echo "\nChecking containers..."
        docker ps -a
        
        # Test database migration
        echo "\nTesting database migration..."
        make db-show
        
        # Clean up
        echo "\nCleaning up..."
        make docker-down
