name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Docker image settings
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Database settings
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: lifemanager
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lifemanager
  PYTHONPATH: ${{ github.workspace }}
  # Use the GitHub token for authentication
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: "1.7.0"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        driver-opts: image=moby/buildkit:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Install Python dependencies
      run: |
        poetry install
        poetry run lint
        poetry run test
        poetry run coverage
        poetry run clean

    - name: Build & Run Containers
      run: |
        echo "\nTesting Build & Run docker commands..."
        cp .env.example .env
        poetry run docker-up
        echo "\nChecking containers..."
        docker ps -a

        # Test database migration
        echo "\nTesting database migration..."
        poetry run db-show

        # Clean up
        echo "\nCleaning up..."
        poetry run docker-down

    - name: Build and push API Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./api/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.repository.created_at }}
          org.opencontainers.image.title=Life Manager API
          org.opencontainers.image.description="Life Manager API"

    - name: Build and push app docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-app:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.repository.created_at }}
          org.opencontainers.image.title=Domusai
          org.opencontainers.image.description="DomusAI : Agentic Life"
