name: Deploy to Azure

on:
  push:
    branches: ["main"]

env:
  DOCKER_HUB_REPOSITORY: "your-dockerhub-username/life-manager"
  RESOURCE_GROUP: "your_resource_group"
  CONTAINER_APP_NAME: "life-manager"
  CONTAINER_APP_ENVIRONMENT: "life-manager-env"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      uses: azure/CLI@v1
      with:
        azcliversion: 2.40.0
        inlineScript: |
          az extension add --name containerapp --upgrade
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.DOCKER_HUB_REPOSITORY }}:latest
