name: Deploy to Azure

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

env:
  DOCKER_HUB_REPOSITORY: "roshangautam/life-manager"
  RESOURCE_GROUP: "life-manager-rg"
  CONTAINER_APP_NAME: "life-manager"
  CONTAINER_APP_ENVIRONMENT: "life-manager-env"

jobs:
  check-ci:
    runs-on: ubuntu-latest
    outputs:
      ci-success: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check CI status
        id: check-ci
        run: |
          echo "CI workflow result: ${{ github.event.workflow_run.conclusion }}"
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "::error::CI workflow did not succeed"
            exit 1
          fi

  deploy:
    needs: check-ci
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      uses: azure/CLI@v1
      with:
        azcliversion: 2.40.0
        inlineScript: |
          az extension add --name containerapp --upgrade
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.DOCKER_HUB_REPOSITORY }}:latest

  manual-approval:
    needs: [check-ci]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: "roshangautam"
          instructions: "Please approve this deployment"
